forms/book_form.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired, Length


class CreateBookForm(FlaskForm):

    name = StringField("Book Name", validators=[DataRequired(), Length(min=3)])
    author = StringField("Author Name", validators=[DataRequired(), Length(min=3, max=30)])
    description = TextAreaField("Book Description")
    cover = StringField("Cover Link")

    save = SubmitField("Create Book")


class EditBookForm(FlaskForm):

    id = StringField("Book Id")
    name = StringField("Book Name", validators=[DataRequired(), Length(min=3)])
    author = StringField("Author Name", validators=[DataRequired(), Length(min=3, max=30)])
    description = TextAreaField("Book Description")
    cover = StringField("Cover Link")

    save = SubmitField("Edit Book")

forms/reservation_form.py
from flask_wtf import FlaskForm
from wtforms import SelectField, SubmitField, StringField
from wtforms.fields.html5 import DateField
from wtforms.validators import InputRequired
from forms.custom_validators import DateGreaterThan


class CreateReservationForm(FlaskForm):
    user = SelectField("User", validators=[InputRequired()])
    book = SelectField("Book", validators=[InputRequired()])
    reservation_date = DateField("Reservation Date", format='%Y-%m-%d', validators=[InputRequired()])
    reservation_expiration_date = DateField("Reservation Expiration Date",
                                            format='%Y-%m-%d',
                                            validators=[DateGreaterThan(fieldname="reservation_date",
                                                                        date_format="%Y-%m-%d")])

    save = SubmitField("Save reservation")


class EditReservationForm(FlaskForm):
    user = StringField("User")
    book = StringField("Book")
    reservation_date = DateField("Reservation Date", format='%Y-%m-%d', validators=[InputRequired()])
    reservation_expiration_date = DateField("Reservation Expiration Date",
                                            format='%Y-%m-%d',
                                            validators=[DateGreaterThan(fieldname="reservation_date",
                                                                        date_format="%Y-%m-%d")])
    save = SubmitField("Edit reservation")

forms/user_form.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField
from wtforms.validators import DataRequired, Length, Email, EqualTo


class CreateUserForm(FlaskForm):
    first_name = StringField("First Name", validators=[DataRequired(), Length(min=2)])
    last_name = StringField("Last Name", validators=[DataRequired(), Length(min=2)])
    email = StringField("Email", validators=[DataRequired(), Email()])
    confirm_email = StringField("Confirm Email", validators=[DataRequired(),
                                                             Email(),
                                                             EqualTo(fieldname="email",
                                                                     message="Emails do not match")])

    save = SubmitField("Create User")


class EditUserForm(FlaskForm):

    id = StringField("User Id")
    first_name = StringField("First Name", validators=[DataRequired(), Length(min=2)])
    last_name = StringField("Last Name", validators=[DataRequired(), Length(min=2)])

    email = StringField("Email")

    save = SubmitField("Edit User")

blueprints/book_blueprint.py
from flask import Blueprint, render_template, flash, url_for, redirect, request

from forms.book_form import CreateBookForm, EditBookForm

import service

books = Blueprint("books", __name__)


@books.route("/books", methods=["GET"])
def get_all_books():
    # flash("My error text1", "danger")
    # flash("Good", "success")
    all_books = service.get_all_books()
    return render_template("books.html", all_books=all_books, title="Books")


@books.route("/books/<book_id>", methods=["GET", "POST"])
def edit_book(book_id):
    response = service.get_book(book_id)
    if response.ok:
        book = response.json()
    else:
        flash("There was an error getting the book details", "danger")
        return redirect(url_for("books.get_all_books"))
    form = EditBookForm()
    if request.method == "POST":
        if form.validate_on_submit():
            response = service.edit_book(book_id=form.id.data,
                                         name=form.name.data,
                                         author=form.author.data,
                                         description=form.description.data,
                                         cover=form.cover.data)
            if response.ok:
                flash(f"Book '{form.name.data}' was successfully saved", "success")
                return redirect(url_for("books.get_all_books"))
            else:
                flash(f"There was an error saving the book because {response.text}", "danger")
        else:
            flash("An error has occurred! Please fix all errors and try again.", "danger")
    else:
        form.id.data = book["id"]
        form.name.data = book["name"]
        form.author.data = book["author"]
        form.description.data = book.get("description")
        form.cover.data = book.get("cover")
    return render_template("edit_book.html", title="Edit Book", form=form, book=book)


@books.route("/books/create", methods=["GET", "POST"])
def create_book():
    form = CreateBookForm()
    if request.method == "POST":
        if form.validate_on_submit():
            response = service.create_book(name=form.name.data,
                                           author=form.author.data,
                                           description=form.description.data,
                                           cover=form.cover.data)
            if response.ok:
                flash(f"Book '{form.name.data}' was successfully saved", "success")
                return redirect(url_for("books.get_all_books"))
            else:
                flash(f"There was an error saving the book because {response.text}", "danger")
        else:
            flash("An error has occurred! Please fix all errors and try again.", "danger")
    return render_template("create_book.html", title="Create Book", form=form)


@books.route("/books/delete/<book_id>", methods=["POST"])
def delete_book(book_id):
    response = service.delete_book(book_id=book_id)
    if response.ok:
        flash(f"Book with id: {book_id} has been successfully deleted!", "success")
    else:
        flash(f"There was a problem deleting the book. Please try again!", "danger")
    return redirect(url_for("books.get_all_books"))

blueprints/reservation_blueprint.py
import datetime

from flask import Blueprint, render_template, flash, url_for, redirect, request

from forms.reservation_form import CreateReservationForm, EditReservationForm

import service

reservations = Blueprint("reservations", __name__)


@reservations.route("/reservations", methods=["GET"])
def get_all_reservations():
    all_reservations = service.get_all_reservations()
    return render_template("reservations.html", all_reservations=all_reservations, title="Reservations")


@reservations.route("/reservations/create", methods=["GET", "POST"])
def create_reservation():
    all_users = service.get_all_users()
    all_existing_books = service.get_all_books()
    all_reservations = service.get_all_reservations()
    all_books = [book for book in all_existing_books
                 if book not in [reservation["book"] for reservation in all_reservations]]

    book_names = [(book["id"], book["name"]) for book in all_books]
    user_names = [(user["id"], f"{user['first_name']} {user['last_name']}") for user in all_users]

    form = CreateReservationForm()
    form.user.choices = user_names
    form.book.choices = book_names
    if request.method == "POST":
        if form.validate_on_submit():
            response = service.create_reservation(book_id=form.book.data,
                                                  user_id=form.user.data,
                                                  reservation_date=form.reservation_date.data,
                                                  reservation_expiration_date=form.reservation_expiration_date.data)
            if response.ok:
                flash("Reservation was successfully saved", "success")
                return redirect(url_for("reservations.get_all_reservations"))
            else:
                flash(f"There was a problem saving the reservation because {response.text}. Please try again!", "danger")
        else:
            flash("There was an error saving the reservation", "danger")
    return render_template("create_reservation.html", form=form, title="Create Reservation")


@reservations.route("/reservations/user/<user_id>/book/<book_id>", methods=["GET", "POST"])
def edit_reservation(user_id, book_id):
    form = EditReservationForm()
    response = service.get_reservation(user_id=user_id, book_id=book_id)
    if response.ok:
        reservation = response.json()
        if request.method == "POST":
            if form.validate_on_submit():
                response = service.update_reservation(user_id=user_id,
                                                      book_id=book_id,
                                                      reservation_date=form.reservation_date.data,
                                                      reservation_expiration_date=form.reservation_expiration_date.data)
                if response.ok:
                    flash("Reservation was saved successfully", "success")
                    return redirect(url_for("reservations.get_all_reservations"))
                else:
                    flash("There was an error editing the reservation. Please fix the errors and try again", "danger")
        else:
            form.book.data = reservation["book"]["name"]
            user = reservation["user"]
            form.user.data = f"{user['first_name']} {user['last_name']}"
            form.reservation_date.data = datetime.datetime.strptime(reservation["reservation_date"], "%Y-%m-%d")
            if reservation["reservation_expiration_date"]:
                form.reservation_expiration_date.data = datetime.datetime.strptime(reservation["reservation_expiration_date"], "%Y-%m-%d")
    else:
        flash("There was an error editing the reservation. Please try again", "danger")
        return redirect(url_for("reservations.get_all_reservations"))
    return render_template("edit_reservation.html", form=form, title="Edit Reservation")


@reservations.route("/reservations/delete/user/<user_id>/book/<book_id>", methods=["POST"])
def delete_reservation(user_id, book_id):
    response = service.delete_reservation(user_id=user_id, book_id=book_id)
    if response.ok:
        flash(f"Reservation for user with id: {user_id} and book with id: "
              f"{book_id} has been successfully deleted!", "success")
    else:
        flash(f"There was a problem deleting the reservation because {response.text}. Please try again!", "danger")
    return redirect(url_for("reservations.get_all_reservations"))

blueprints/user_blueprint.py
from flask import Blueprint, render_template, flash, url_for, redirect, request

from forms.user_form import CreateUserForm, EditUserForm

import service

users = Blueprint("users", __name__)


@users.route("/users", methods=["GET"])
def get_all_users():
    all_users = service.get_all_users()
    return render_template("users.html", all_users=all_users, title="Users")


@users.route("/users/create", methods=["GET", "POST"])
def create_user():
    form = CreateUserForm()
    if request.method == "POST":
        if form.validate_on_submit():
            response = service.create_user(first_name=form.first_name.data,
                                           last_name=form.last_name.data,
                                           email=form.email.data)
            if response.ok:
                flash(f"User with name {form.first_name.data} {form.last_name.data} was created successfully", "success")
                return redirect(url_for("users.get_all_users"))
            else:
                flash(f"There was an error saving the user because: {response.text}. Please try again!", "danger")
        else:
            flash(f"There was an error saving the user. Please fix all issues and try again!", "danger")
    return render_template("create_user.html", title="Create User", form=form)


@users.route("/users/<user_id>", methods=["GET", "POST"])
def edit_user(user_id):
    response = service.get_user(user_id=user_id)
    if response.ok:
        user = response.json()
    else:
        flash(f"Unable to retrieve user by user id: {user_id}", "danger")
        return redirect(url_for("users.get_all_users"))
    form = EditUserForm()
    if request.method == "POST":
        if form.validate_on_submit():
            response = service.edit_user(user_id=form.id.data,
                                         first_name=form.first_name.data,
                                         last_name=form.last_name.data,
                                         email=form.email.data)
            if response.ok:
                flash(f"User with id: {user_id} was edited successfully", "success")
                return redirect(url_for("users.get_all_users"))
            else:
                flash(f"There was an error saving the user because {response.text}", "danger")
        else:
            flash("There was an error editing the user", "danger")
    else:
        form.first_name.data = user["first_name"]
        form.last_name.data = user["last_name"]
        form.id.data = user["id"]
        form.email.data = user["email"]
    return render_template("edit_user.html", title="Edit User", form=form)


@users.route("/users/delete/<user_id>", methods=["POST"])
def delete_user(user_id):
    response = service.delete_user(user_id=user_id)
    if response.ok:
        flash(f"User with id: {user_id} has been successfully deleted!", "success")
    else:
        flash(f"There was a problem deleting the user because {response.text}. Please try again!", "danger")
    return redirect(url_for("users.get_all_users"))

templates/books.html
{% extends "layout.html" %}
{% set active_page = "books" %}
{% from "delete_modal.html" import show_delete_modal%}
{% from "view_book_modal.html" import book_details_modal %}
{% block content %}
<div class="container-fluid">
    <div class="row">
        <div class="btn-group my-3 col-8" role="group" aria-label="User Actions">
            <button type="button" id="viewDetails" class="btn btn-secondary" disabled data-toggle="modal" data-target="#viewBookDetails"> View Details</button>
            <a id="create" href="{{url_for('books.create_book')}}" class="btn btn-secondary">Create</a>
            <button type="button" id="edit" class="btn btn-secondary" disabled>Edit</button>
            <button type="button" id="delete" class="btn btn-secondary" disabled data-toggle="modal" data-target="#deleteModal" data-page="Book">Delete</button>
        </div>
        <div class="col-4 my-3">
            <input type="search" id="searchField" value="" class="form-control" placeholder="Search">
        </div>
    </div>
</div>
<div class="container-fluid">
    <table class="table table-hover" id="table">
        <thead class="thead-dark">
        <tr>
            <th scope="col" style="width: 10%">#</th>
            <th scope="col" style="width: 45%">Book Name</th>
            <th scope="col" style="width: 45%">Book Author</th>
        </tr>
        </thead>
        <tbody>
        {%for book in all_books %}
        <tr class="clickable-row" id="{{book.id}}" data-hidden="true" data-book='{{book|to_json}}'  data-id="{{book.id}}">
            <th scope="row">{{loop.index}}</th>
            <td>{{book.name}}</td>
            <td>{{book.author}}</td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
{{show_delete_modal()}}
{{book_details_modal()}}
{%endblock content%}

templates/create_book.html
{% extends "layout.html" %}
{% set active_page = "books" %}
{% block content %}
<div class="content-section mx-5">
    <form method="post" action="">
        {{form.hidden_tag()}}
        <fieldset class="form-group">
            <div class="form-group">
                {{form.name.label(class="form-control-label")}}
                {% if form.name.errors %}
                    {{form.name(class="form-control form-control is-invalid")}}
                    <span class="invalid-feedback" id="name_error">
                        {% for error in form.name.errors %}
                            {{error}}
                        {% endfor %}
                    </span>
                {% else %}
                    {{form.name(class="form-control form-control")}}
                {% endif%}
            </div>
            <div class="form-group">
                {{form.author.label(class="form-control-label")}}
                {% if form.author.errors %}
                    {{form.author(class="form-control form-control is-invalid")}}
                    <span class="invalid-feedback" id="author_error">
                        {% for error in form.author.errors %}
                            {{error}}
                        {% endfor %}
                    </span>
                {% else %}
                    {{form.author(class="form-control form-control")}}
                {% endif%}
            </div>
            <div class="form-group">
                {{form.description.label(class="form-control-label")}}
                {{form.description(class="form-control form-control")}}
            </div>
            <div class="form-group">
                {{form.cover.label(class="form-control-label")}}
                {{form.cover(class="form-control form-control")}}
            </div>
        </fieldset>
        <div class="form-group">
            {{form.save(class="btn btn-primary")}}
            <a class="btn btn-link" id="back" href="{{url_for('books.get_all_books')}}">Cancel</a>
        </div>
    </form>
</div>
{% endblock content %}

templates/create_reservation.html
{% extends "layout.html" %}
{% set active_page = "reservations" %}
{% block content %}
<div class="content-section mx-5">
    <form method="post" action="">
        {{form.hidden_tag()}}
        <fieldset class="form-group">
            <div class="form-group">
                {{form.user.label(class="form-control-label")}}
                {{form.user(class="form-control")}}
            </div>
            <div class="form-group">
                {{form.book.label(class="form-control-label")}}
                {{form.book(class="form-control")}}
            </div>
            <div class="form-group">
                {{form.reservation_date.label(class="form-control-label")}}
                {{form.reservation_date(class='datepicker form-control', id='reservation_date')}}
            </div>
            <div class="form-group">
                {{form.reservation_expiration_date.label(class="form-control-label")}}
                {% if form.reservation_expiration_date.errors %}
                    {{form.reservation_expiration_date(class='datepicker form-control is-invalid', id='reservation_expiration_date')}}
                    {% for error in form.reservation_expiration_date.errors %}
                        <span class="invalid-feedback" id="reservation_expiration_date_error">
                            {{error}}
                        </span>
                    {% endfor %}
                {% else %}
                    {{form.reservation_expiration_date(class='datepicker form-control', id='reservation_expiration_date')}}
                {% endif %}

            </div>
        </fieldset>
        <div class="form-group">
            {{form.save(class="btn btn-primary")}}
            <a class="btn btn-link" id="back" href="{{url_for('reservations.get_all_reservations')}}">Cancel</a>
        </div>
    </form>
</div>
{% endblock content %}

templates/create_user.html
{% extends "layout.html" %}
{% set active_page = "users" %}
{% block content %}
<div class="content-section mx-5">
    <form method="post" action="">
        {{form.hidden_tag()}}
        <fieldset class="form-group">
            <div class="form-group">
                {{form.first_name.label(class="form-control-label")}}
                {% if form.first_name.errors %}
                    {{form.first_name(class="form-control is-invalid")}}
                    {% for error in form.first_name.errors %}
                        <span class="invalid-feedback" id="first_name_error">
                            {{error}}
                        </span>
                    {% endfor %}
                {% else %}
                    {{form.first_name(class="form-control")}}
                {% endif %}
            </div>
            <div class="form-group">
                {{form.last_name.label(class="form-control-label")}}
                {% if form.last_name.errors %}
                    {{form.last_name(class="form-control is-invalid")}}
                    {% for error in form.last_name.errors %}
                        <span class="invalid-feedback" id="last_name_error">
                            {{error}}
                        </span>
                    {% endfor %}
                {% else %}
                    {{form.last_name(class="form-control")}}
                {% endif %}
            </div>
            <div class="form-group">
                {{form.email.label(class="form-control-label")}}
                {% if form.email.errors %}
                    {{form.email(class="form-control is-invalid")}}
                    {% for error in form.email.errors %}
                        <span class="invalid-feedback" id="email_error">
                            {{error}}
                        </span>
                    {% endfor %}
                {% else %}
                    {{form.email(class="form-control")}}
                {% endif %}
            </div>
            <div class="form-group">
                {{form.confirm_email.label(class="form-control-label")}}
                {% if form.confirm_email.errors %}
                    {{form.confirm_email(class="form-control is-invalid")}}
                    {% for error in form.confirm_email.errors %}
                        <span class="invalid-feedback" id="confirm_email_error">
                            {{error}}
                        </span>
                    {% endfor %}
                {% else %}
                    {{form.confirm_email(class="form-control")}}
                {% endif %}
            </div>
        </fieldset>
        <div class="form-group">
            {{form.save(class="btn btn-primary")}}
            <a class="btn btn-link" id="back" href="{{url_for('users.get_all_users')}}">Cancel</a>
        </div>
    </form>
</div>
{% endblock content %}

templates/delete_modal.html
 {% macro show_delete_modal() -%}
   <!-- Modal -->
    <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalTitle" aria-hidden="true">
      <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="deleteModalTitle">Delete</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
              <div id="deleteMessage">"Are you sure you want to delete the selected book?"</div>
          </div>
          <div class="modal-footer">
            <form method="post" id="submitDelete" action="">
                <button type="button" class="btn btn-link" id="modalCancelButton" data-dismiss="modal">Cancel</button>
                <input type="submit" value="Delete" class="btn btn-primary" id="modelDelButton">
            </form>
          </div>
        </div>
      </div>
    </div>
{%- endmacro %}

templates/delete_reservation_modal.html
 {% macro show_delete_reservation_modal() -%}
   <!-- Modal -->
    <div class="modal fade" id="deleteReservationModal" tabindex="-1" role="dialog" aria-labelledby="deleteReservationModalTitle" aria-hidden="true">
      <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="deleteReservationModalTitle">Delete</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
              <div id="deleteReservationMessage">"Are you sure you want to delete the selected reservation?"</div>
          </div>
          <div class="modal-footer">
            <form method="post" id="submitReservationDelete" action="">
                <button type="button" class="btn btn-link" id="modalCancelReservationButton" data-dismiss="modal">Cancel</button>
                <input type="submit" value="Delete" class="btn btn-primary" id="modelDelReservationButton">
            </form>
          </div>
        </div>
      </div>
    </div>
{%- endmacro %}

templates/reservations.html
{% extends "layout.html" %}
{% set active_page = "reservations" %}
{% from "delete_reservation_modal.html" import show_delete_reservation_modal%}
{% block content %}
     <div class="container-fluid">
        <div class="row">
            <div class="btn-group my-3 col-8" role="group" aria-label="User Actions">
              <a id="create-reservation" href="{{url_for('reservations.create_reservation')}}" class="btn btn-secondary">Create</a>
              <button type="button" id="edit-reservation" class="btn btn-secondary" disabled>Edit</button>
              <button type="button" id="delete-reservation" class="btn btn-secondary" disabled data-toggle="modal" data-target="#deleteReservationModal" data-page="Reservation">Delete</button>
            </div>
            <div class="col-4 my-3">
                <input type="search" id="searchField" value="" class="form-control" placeholder="Search">
            </div>
        </div>
     </div>
    <div class="container-fluid ">
        <table class="table table-striped table-hover" id="table">
          <thead class="thead-dark">
            <tr>
              <th scope="col" style="width: 5%">#</th>
              <th scope="col" style="width: 10%">User First Name</th>
              <th scope="col" style="width: 10%">User Last Name</th>
              <th scope="col" style="width: 15%">User Email</th>
              <th scope="col" style="width: 25%">Book Name</th>
              <th scope="col" style="width: 15%">Book Author</th>
              <th scope="col" style="width: 10%">Reservation Date</th>
              <th scope="col" style="width: 10%">Reservation Expiration Date</th>
            </tr>
          </thead>
          <tbody>
          {%for reservation in all_reservations %}
              <tr class="clickable-reservation-row" id="{{reservation.user.id}}_{{reservation.book.id}}"
                  data-hidden="true" data-userid="{{reservation.user.id}}" data-bookid="{{reservation.book.id}}">
                  <th scope="row">{{loop.index}}</th>
                  <td>{{reservation.user.first_name}}</td>
                  <td>{{reservation.user.last_name}}</td>
                  <td style="word-break: break-all">{{reservation.user.email}}</td>
                  <td>{{reservation.book.name}}</td>
                  <td>{{reservation.book.author}}</td>
                  <td>{{reservation.reservation_date}}</td>
                  <td>{{reservation.reservation_expiration_date}}</td>
              </tr>
          {% endfor %}
          </tbody>
        </table>
    </div>
{{show_delete_reservation_modal()}}
{%endblock%}

templates/users.html
{% extends "layout.html" %}
{% from "delete_modal.html" import show_delete_modal%}
{% from "view_user_modal.html" import user_details_modal %}
{% set active_page = "users" %}
{% block content %}
<div class="container-fluid">
    <div class="row">
        <div class="btn-group my-3 col-8" role="group" aria-label="User Actions">
            <button type="button" id="viewUserDetails" class="btn btn-secondary" disabled data-toggle="modal"
                    data-target="#viewUserDetailsModal">View Details
            </button>
            <a href="{{url_for('users.create_user')}}" id="create" class="btn btn-secondary">Create</a>
            <button type="button" id="edit" class="btn btn-secondary" disabled>Edit</button>
            <button type="button" id="delete" class="btn btn-secondary" disabled data-toggle="modal"
                    data-target="#deleteModal" data-page="User">Delete
            </button>
        </div>
        <div class="col-4 my-3">
            <input type="search" id="searchField" value="" class="form-control" placeholder="Search">
        </div>
    </div>
</div>
<div class="container-fluid">
    <table class="table table-hover" id="table">
        <thead class="thead-dark">
        <tr>
            <th scope="col" style="width: 10%">#</th>
            <th scope="col" style="width: 30%">User First Name</th>
            <th scope="col" style="width: 30%">User Last Name</th>
            <th scope="col" style="width: 30%">User Email</th>
        </tr>
        </thead>
        <tbody>
        {%for user in all_users %}
        <tr class="clickable-row" id="{{user.id}}" data-hidden="true" data-user="{{user|to_json}}"   data-id="{{user.id}}">
            <th scope="row">{{loop.index}}</th>
            <td>{{user.first_name}}</td>
            <td>{{user.last_name}}</td>
            <td>{{user.email}}</td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
{{show_delete_modal()}}
{{user_details_modal()}}
{%endblock%}

templates/view_book_modal.html
{% macro book_details_modal() -%}
<div class="modal fade" id="viewBookDetails" tabindex="-1" role="dialog" aria-labelledby="viewBookDetails"
     aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="itemLabel">Book Details</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body" id="modal-body">
                <div class="media">
                    <img src="{{url_for('static', filename='no_cover.gif')}}" class="mr-3" alt="Image" id="preview"
                         height="300" width="200">
                    <div class="media-body">
                        <h3 class="mt-0" id="book_name">Book Name</h3>
                        <h5 class="mt-0" id="book_author"> Authors:</h5>
                        <span id="book_description">
                          Placeholder for a short description
                      </span>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-link" id="viewBookCancelButton" data-dismiss="modal">Cancel
                </button>
            </div>
        </div>
    </div>
</div>
{%- endmacro %}